### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Dhruv122**

### CODE REVIEW

**Comment by Dhruv122** [comment]
Please yaar accept kar lo I am a student sikh raha hu please🙏 kardena please

**Review by sakshi13-m — APPROVED** [review]
Hacktober accepted

**Comment by Dhruv122** [comment]
But why you closed my another pull request😔

**Comment by Dhruv122** [comment]
> Hacktober accepted

Why you closed my another pull request 😔 please accept 🙏🙏

**Comment by sakshi13-m** [comment]
sorry i can't because that would be against the rule one pull request for small edit is fine but more than that will not be considered by them also.

**Pull request merged**
